@host = http://localhost:3000


### Create a new customer
POST {{host}}/customer
Content-Type: application/json

{
    "nombre_cliente": "Juan",
    "apellido_cliente": "Pérez",
    "correo_cliente": "juan.perez@example.com",
    "contrasena_cliente": "secret123",
    "telefono_cliente": "0987654321",
    "direccion": "Av. Siempre Viva 742",
    "estado_cliente": "Activo"
}

### Get all customers
GET {{host}}/customer
Accept: application/json

### Get customer by id
GET {{host}}/customer/1
Accept: application/json

### Update customer by id
PATCH {{host}}/customer/1
Content-Type: application/json

{
    "telefono_cliente": "0999999998"
}

### Delete customer by id
DELETE {{host}}/customer/1
Accept: application/json

### Create a new employee
POST {{host}}/employee
Content-Type: application/json

{
    "nombre_empleado": "Carlos",
    "apellido_empleado": "Lopez",
    "correo_empleado": "carlos.lopez@example.com",
    "contrasena_empleado": "password123",
    "telefono_empleado": "1234567890",
    "cargo": "Desarrollador",
    "estado_empleado": "Activo"
}

### Get all employees
GET {{host}}/employee
Accept: application/json

### Get employee by id
GET {{host}}/employee/1
Accept: application/json

### Update employee by id
PATCH {{host}}/employee/1
Content-Type: application/json
{
    "telefono_empleado": "0987654321"
}

### Delete employee by id
DELETE {{host}}/employee/1
Accept: application/json

### Product endpoints

### Create a new product
POST {{host}}/products
Content-Type: application/json

{
    "nombre_producto": "Hamburguesa Clásica",
    "descripcion": "Carne 100% res, pan artesanal, lechuga, tomate",
    "ingredientes": "Carne, pan, lechuga, tomate, aderezo",
    "precio": 7.50,
    "foto": "https://example.com/img/hamburguesa.jpg",
    "disponibilidad": "disponible"
}

### Get all products
GET {{host}}/products
Accept: application/json

### Get available products
GET {{host}}/products/available
Accept: application/json

### Get product by id
GET {{host}}/products/1
Accept: application/json

### Update product by id
PATCH {{host}}/products/1
Content-Type: application/json

{
    "precio": 8.00,
    "disponibilidad": "no disponible"
}

### Delete product by id
DELETE {{host}}/products/1
Accept: application/json
